version: '3.5'

services:
  postgis:
    container_name: timescaledb
    image: timescale/timescaledb-postgis
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgis}
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - "15432:5432"
    expose:
      - "15432"
    networks:
      - postgres
    restart: unless-stopped
  
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@ubica.ec}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-postgis}
    volumes:
       - pgadmin:/root/.pgadmin
    ports:
      - "${PGADMIN_PORT:-8500}:80"
    networks:
      - postgres
    restart: unless-stopped

  geoserver:
      image: kartoza/geoserver:2.15.0
      volumes:
        - geoserver-data:/opt/geoserver/data_dir
      ports:
        - "8600:8080"
      restart: on-failure
      #env_file:
      #  - docker-env/geoserver.env
      networks:
        - postgres  

  webspoon:
    image: hiromuhota/webspoon
    ports:
      - "8700:8080"
    volumes:
      - kettle:/home/tomcat/.kettle
      - pentaho:/home/tomcat/.pentaho
      - ../data:/home/tomcat/.kettle/data
      - ./transformations:/home/tomcat/.kettle/transformations
    environment:
      - "JAVA_OPTS=-Xms1024m -Xmx2048m"
    networks:
        - postgres         

networks:
  postgres:
    driver: bridge

volumes:
    postgres:
    pgadmin:
    geoserver-data:
    kettle:
    pentaho: